language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python manage.py cov

after_success:
  coveralls
